spring:
  profiles:
    active: cloud
---
spring:
  profiles: cloud
  jpa:
    show_sql: false
    database: mysql
    hibernate:
      ddl-auto: create-drop
---
spring:
  profiles: test
  jpa:
    show_sql: true
    database: h2
    hibernate:
      ddl-auto: create-drop
